<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>RunAfterTestMethodCallbacks.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">spring-test</a> &gt; <a href="index.source.html" class="el_package">org.springframework.test.context.junit4.statements</a> &gt; <span class="el_source">RunAfterTestMethodCallbacks.java</span></div><h1>RunAfterTestMethodCallbacks.java</h1><pre class="source lang-java linenums">/*
 * Copyright 2002-2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.test.context.junit4.statements;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

import org.junit.runners.model.MultipleFailureException;
import org.junit.runners.model.Statement;

import org.springframework.test.context.TestContextManager;

/**
 * {@code RunAfterTestMethodCallbacks} is a custom JUnit {@link Statement} which allows
 * the &lt;em&gt;Spring TestContext Framework&lt;/em&gt; to be plugged into the JUnit execution chain
 * by calling {@link TestContextManager#afterTestMethod afterTestMethod()} on the supplied
 * {@link TestContextManager}.
 *
 * &lt;p&gt;&lt;strong&gt;NOTE:&lt;/strong&gt; This class requires JUnit 4.9 or higher.
 *
 * @author Sam Brannen
 * @since 3.0
 * @see #evaluate()
 * @see RunBeforeTestMethodCallbacks
 */
public class RunAfterTestMethodCallbacks extends Statement {

	private final Statement next;

	private final Object testInstance;

	private final Method testMethod;

	private final TestContextManager testContextManager;


	/**
	 * Construct a new {@code RunAfterTestMethodCallbacks} statement.
	 * @param next the next {@code Statement} in the execution chain
	 * @param testInstance the current test instance (never {@code null})
	 * @param testMethod the test method which has just been executed on the
	 * test instance
	 * @param testContextManager the TestContextManager upon which to call
	 * {@code afterTestMethod()}
	 */
	public RunAfterTestMethodCallbacks(Statement next, Object testInstance, Method testMethod,
<span class="fc" id="L62">			TestContextManager testContextManager) {</span>

<span class="fc" id="L64">		this.next = next;</span>
<span class="fc" id="L65">		this.testInstance = testInstance;</span>
<span class="fc" id="L66">		this.testMethod = testMethod;</span>
<span class="fc" id="L67">		this.testContextManager = testContextManager;</span>
<span class="fc" id="L68">	}</span>


	/**
	 * Evaluate the next {@link Statement} in the execution chain (typically an instance of
	 * {@link org.junit.internal.runners.statements.RunAfters RunAfters}), catching any
	 * exceptions thrown, and then invoke
	 * {@link TestContextManager#afterTestMethod(Object, Method, Throwable)} supplying the
	 * first caught exception (if any).
	 * &lt;p&gt;If the invocation of {@code afterTestMethod()} throws an exception, that
	 * exception will also be tracked. Multiple exceptions will be combined into a
	 * {@link MultipleFailureException}.
	 */
	@Override
	public void evaluate() throws Throwable {
<span class="fc" id="L83">		Throwable testException = null;</span>
<span class="fc" id="L84">		List&lt;Throwable&gt; errors = new ArrayList&lt;&gt;();</span>
		try {
<span class="fc" id="L86">			this.next.evaluate();</span>
		}
<span class="fc" id="L88">		catch (Throwable ex) {</span>
<span class="fc" id="L89">			testException = ex;</span>
<span class="fc" id="L90">			errors.add(ex);</span>
<span class="fc" id="L91">		}</span>

		try {
<span class="fc" id="L94">			this.testContextManager.afterTestMethod(this.testInstance, this.testMethod, testException);</span>
		}
<span class="fc" id="L96">		catch (Throwable ex) {</span>
<span class="fc" id="L97">			errors.add(ex);</span>
<span class="fc" id="L98">		}</span>

<span class="fc" id="L100">		MultipleFailureException.assertEmpty(errors);</span>
<span class="fc" id="L101">	}</span>

}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.3.201901230119</span></div></body></html>